### ISSUE TITLE
Folder location of sf2

### ISSUE THREAD

**Issue by fantomas** [LeaseWeb/LswRemoteTemplateBundle#4]
I am using symfony 1.4 and if I place sf2 folder next to apps how does the htaccess rule works? I cannot internally redirect to sf2/web folder which is not public.

My folder structure:
-apps
-sf2
--web
--.htaccess
--app.php
-web (public folder)
--.htaccess (here comes the htaccess rule described in the docs)
--index.php

**Comment by mevdschee** [comment]
I suggest you symlink the web directory of sf2 in the web directory of sf1. But any other method would work equally well.
